# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'StoreApplication'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(solutionPath)
  displayName: 'dotnet build $(buildConfiguration) $(solutionPath)'
# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Project1-StoreApplication'
    appType: 'webApp'
    WebAppName: 'rodsalomon-StoreApplication'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip')'
    zipAfterPublish: True

# - task: AzureRmWebAppDeployment@3
#   inputs:
#     azureSubscription: 'Project1'
#     WebAppName: 'rodsalomon-storeapplication'
#     Package: $(System.ArtifactsDirectory)/**/*.zip



