# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'StoreApplication'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(solutionPath)
  displayName: 'dotnet build $(buildConfiguration) $(solutionPath)'
- script: dotnet restore
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'StoreApplication.WebUI/StoreApplication.WebUI.csproj'
    arguments: '--configuration Release' # Update this to match your need
# ...
# do this near the end of your pipeline in most cases
- task: PublishBuildArtifacts@1
