# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'StoreApplication'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-rodsalomon'
    organization: 'rodsalomon10-github'
    scannerMode: 'MSBuild'
    projectKey: 'rodsalomon-storeapplication'
    extraProperties: 
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"


- script: dotnet build --configuration $(buildConfiguration) $(solutionPath)
  displayName: 'dotnet build $(buildConfiguration) $(solutionPath)'


- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: SonarCloudAnalyze@1
  inputs: {}

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '60'


- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Project1-StoreApplication'
    appType: 'webApp'
    WebAppName: 'rodsalomon-StoreApplication'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'





